{{- if and .Values.enabled (or .Values.users .Values.roles) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: idam-identities-importer
  labels:
    app.kubernetes.io/name: idam-identities-importer
    app.kubernetes.io/instance: {{ .Release.Name }}-idam-identities-importer
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "3"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      name: idam-identities-importer
      labels:
        app.kubernetes.io/name: idam-identities-importer
    spec:
      volumes:
        - name: vault
          flexVolume:
            driver: azure/kv
            secretRef:
              name: kvcreds
            options:
              tenantid: {{ .Values.global.tenantId }}
              keyvaultname: {{ .Values.global.keyVaultName }}
              keyvaultobjectnames: idam-owner-username;idam-owner-password
              keyvaultobjecttypes: secret;secret
      {{- $global := .Values.global -}}
      {{- if .Values.roles }}
      initContainers:
        {{- range $index, $item := .Values.roles }}
        - name: idam-role-importer-{{ $index }}
          image: hmctspublic.azurecr.io/hmcts/idam/utils:latest
          command: [ /bin/sh ]
          args:
            - -c
            - >-
              IDAM_ADMIN_USER=$(cat /mnt/secrets/idam-owner-username)
              IDAM_ADMIN_PASSWORD=$(cat /mnt/secrets/idam-owner-password)
              /wait && /scripts/create-role.sh
              '{{ .id }}'
          env:
            - name: WAIT_HOSTS
              value: idam-api:80
            - name: IDAM_API_URL
              value: http://idam-api
          volumeMounts:
            - name: vault
              mountPath: /mnt/secrets
              readOnly: true
          resources:
            requests:
              cpu: 25m
              memory: 8Mi
            limits:
              cpu: 50m
              memory: 16Mi
          imagePullPolicy: IfNotPresent
        {{- end }}
      {{- end }}
      {{- if .Values.users }}
      containers:
        {{- range $index, $item := .Values.users }}
        - name: idam-user-importer-{{ $index }}
          image: hmctspublic.azurecr.io/hmcts/idam/utils:latest
          command: [ /bin/sh ]
          args:
            - -c
            - >-
              IDAM_ADMIN_USER=$(cat /mnt/secrets/idam-owner-username)
              IDAM_ADMIN_PASSWORD=$(cat /mnt/secrets/idam-owner-password)
              /wait && /scripts/create-user.sh
              '{{ .email }}'
              '{{ .forename | default "Forename" }}'
              '{{ .surname | default "Surname" }}'
              '{{ .password | default "Password12" }}'
              '{{ .group }}'
              '[{{ range $index, $item := .roles }}{{ if $index }},{{ end }}{{ printf "{\"code\":\"%s\"}" $item }}{{end}}]'
          env:
            - name: WAIT_HOSTS
              value: idam-api:80
            - name: IDAM_API_URL
              value: http://idam-api
          volumeMounts:
            - name: vault
              mountPath: /mnt/secrets
              readOnly: true
          resources:
            requests:
              cpu: 25m
              memory: 8Mi
            limits:
              cpu: 50m
              memory: 16Mi
          imagePullPolicy: IfNotPresent
        {{- end }}
      {{- end }}
      restartPolicy: OnFailure
{{- end }}
