global:
  devMode: true

idam-api:
  java:
    image: hmctspublic.azurecr.io/idam/api:stable
    environment:
      JAVA_OPTS: -Xms256m -Xms768m
      STRATEGIC_API_URL: https://api-{{ .Release.Name }}.service.core-compute-preview.internal
      STRATEGIC_WEBPUBLIC_URL: https://web-{{ .Release.Name }}.service.core-compute-preview.internal
      SPRING_DATASOURCE_URL: jdbc:postgresql://shared-db/openidm?currentSchema=fridam
      SPRING_DATASOURCE_USERNAME: openidm
      SPRING_DATASOURCE_PASSWORD: openidm
      IDAM_SPI_FORGEROCK_AM_ROOT: http://fr-am:8080/openam
      IDAM_SPI_FORGEROCK_AM_TOPLEVELHOST: fr-am
      IDAM_SPI_FORGEROCK_AM_USERNAME: amadmin
      IDAM_SPI_FORGEROCK_AM_PASSWORD: Pa55word11
      IDAM_SPI_FORGEROCK_AM_JWKSURIFOROAUTH2CLIENTS: http://fr-am:8080/openam/oauth2/hmcts/connect/jwk_uri
      IDAM_SPI_FORGEROCK_IDM_ROOT: http://fr-idm:18080/openidm
      IDAM_SPI_FORGEROCK_IDM_USERNAME: openidm-admin
      IDAM_SPI_FORGEROCK_IDM_PASSWORD: openidm-admin
      SECURITY_OAUTH2_CLIENT_CLIENTSECRET: password
      SECURITY_OAUTH2_CLIENT_PRE_ESTABLISHED_REDIRECT_URI: https://web-{{ .Release.Name }}.service.core-compute-preview.internal/login
      SECURITY_OAUTH2_CLIENT_REGISTERED_REDIRECT_URI: https://web-{{ .Release.Name }}.service.core-compute-preview.internal/login
      IDAMHEALTHCHECK_AM_ENABLED: false
      IDAMHEALTHCHECK_IDM_ENABLED: false
      MANAGEMENT_SECURITY_ENABLED: false
      TESTING_SUPPORT_ENABLED: true
      APPSETTING_NODE_PATH: /opt/app
      CACHING_ENABLED: false
    readinessPath: /health
    livenessPath: /health
    replicas: 1
    ingressHost: false
    registerAdditionalDns:
      enabled: true
      primaryIngressHost: '{{ .Release.Name }}.service.core-compute-preview.internal'
      prefix: api

idam-web-public:
  java:
    image: hmctspublic.azurecr.io/idam/web-public:stable
    applicationPort: 8080
    environment:
      JAVA_OPTS: -Xms256m -Xms768m
      STRATEGIC_SERVICE_URL: http://idam-api
      MANAGEMENT_SECURITY_ENABLED: false
    readinessPath: /health
    livenessPath: /health
    replicas: 1
    ingressHost: false
    registerAdditionalDns:
      enabled: true
      primaryIngressHost: '{{ .Release.Name }}.service.core-compute-preview.internal'
      prefix: web
